### ISSUE TITLE
How to run hello()?

### ISSUE THREAD

**Issue by kevinpauli** [maresb/micromamba-devcontainer-example#15]
Hello, I have cloned the project and re-opened in a devcontainer successfully.  Now exactly how do I run the hello() function to prove that the environment was initialized, pulling in the cowsay dependency?  A launch.json would be appreciated, and/or something in the readme showing how to activate the conda env and run hello() from a terminal.

**Comment by maresb** [comment]
Hey, thanks a lot for your interest in this project. I've honestly somewhat given up on this due to bugs in VS Code. Since sometime late last year, the automatic extension installation with caching [has been broken](https://github.com/microsoft/vscode-remote-release/issues/7690), and that sort of defeats the whole point for me.

The docs definitely would need to get cleaned up since there are multiple repos (one for the base image, one for the cookiecutter template, one for the example rendered cookiecutter template), but the main instructions you should be referring to is the [Quickstart](https://github.com/mamba-org/micromamba-devcontainer#quickstart).

When I follow the instructions in the Quickstart, I notice that I don't explain how to open the interactive window. It should be "Ctrl+Shift+P" → "Jupyter: Create Interactive Window" but that doesn't work since the Jupyter extension fails to properly install for unclear reasons (see also the issue I linked above):
![image](https://github.com/maresb/micromamba-devcontainer-example/assets/15216687/73ef47d4-07dc-4ccd-b9c3-d8a21805c3ff)

So a workaround is to click on the extensions button ![image](https://github.com/maresb/micromamba-devcontainer-example/assets/15216687/be4fb487-3f58-4094-9cb4-a64a2d92144b), type "Jupyter" and click on the blue "Install in Dev Container" button. After that, "Ctrl+Shift+P" → "Jupyter: Create Interactive Window" will work. Then you can type the commands as per the quickstart screenshot. The environment should be automatically detected.

I hope that helps a little bit. I'm not sure what to do about the extensions problem though.

**Comment by kevinpauli** [comment]
Are you saying you've given up on the micromamba devcontainer itself, or just on the idea of a cookiecutter/cruft template and example project?

Because I think this whole collection of projects is super promising.  I built something similar internally for a client (starting with the official miniconda devcontainer and installing poetry on it along with a bunch of other stuff) and what you've done here is way simpler and more focused and reusable than what I ended up with, and I like it a lot.

I also like the idea of it being open source so after I leave, this client will not be left high and dry with nobody who wants to touch what I built.  I'm putting together a proposal to rip out what I've done and replace it with your micromamba devcontainer, and our own internal cookiecutter template that allows data scientists to get started developing quickly on new projects.

I'd love to contribute back any improvements but I'm not very familiar with how to contribute to open source however I'm willing to learn if you'll bear with me.

BTW I did eventually figure out how to run the hello() from the command line by adding a main block

```python
if __name__ == "__main__":
    hello()
```

Then I was able to run it from the terminal as I wished:

![image](https://github.com/maresb/micromamba-devcontainer-example/assets/2067494/e64493fe-580f-4ae7-a127-60ced71ffc14)

Also, your response above about notebooks gave me a hint, and I was able to add a notebook and this ran fine, without the need for that __main__ block

![image](https://github.com/maresb/micromamba-devcontainer-example/assets/2067494/600cbb9b-a299-4e79-b79d-b0402b6df17f)

Now in order to run the code, I did have to reload the workspace of course so that pylance et. al. would be happy, but I and my users are both accustomed to that already since my miniconda+poetry devcontainer solution suffered from the same issue.

Let me know if what you think, I would love to see this project continue and am willing to help how I can, if something is lacking.  Honestly been wanting to dip my toe into open source contributions anyway!  😄

**Comment by maresb** [comment]
Ok, excellent! I'm glad you found this helpful. Also it's nice to know that my devcontainer isn't the only one suffering from similar issues.

Due to the reliability issues, I'm not using this dev container as actively as I used to. By giving up I mean that I'm lacking in motivation put in extra effort to turn this into a polished product. Although I did go through the trouble of generating some logs for the above-linked issue in hopes of moving that forward.

I'm happy to accept contributions here, so if you want to improve the docs, fix some bugs, or add general improvements I'm happy to review them.

Did you have any problems getting the Python/Jupyter extensions to install? (This happens to me quite often, and reloading doesn't solve it.)
